import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4fdbcc",
        error: "#ba1a1a",
        "tertiary-container": "#00ac9f",
        "on-primary-container": "#5f1900",
        surface: "#f8f9fa",
        "on-primary": "#ffffff",
        primary: "#ab3500",
        "surface-container-high": "#e7e8e9",
        "error-container": "#ffdad6",
        tertiary: "#006a62",
        "secondary-fixed-dim": "#c4c4df",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-primary-fixed-variant": "#832600",
        "tertiary-fixed": "#70f8e8",
        "secondary-fixed": "#e0e0fc",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#ffb59d",
        "on-secondary-fixed": "#181a2e",
        "secondary-container": "#ddddf9",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1d",
        "surface-container": "#edeeef",
        "on-tertiary": "#ffffff",
        secondary: "#5b5d74",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#390c00",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-container": "#003834",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#005049",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e1bfb5",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#ab3500",
        "on-secondary-container": "#5f6178",
        "primary-fixed-dim": "#ffb59d",
        outline: "#8d7168",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#594139",
        "primary-container": "#ff6b35",
        "on-secondary-fixed-variant": "#43455b",
        "on-error": "#ffffff",
        background: "#f8f9fa",
        "primary-fixed": "#ffdbd0",
        success: "#1b8a5a",
        "success-container": "#d6f5e5",
        warning: "#eab308",
        "warning-container": "#fef3c7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "touch-target-min": "44px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "margin-tablet": "24px",
        "stack-sm": "8px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-table-num": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "numeric-pin": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
